### ISSUE TITLE
我写了一个python版本的GA，大家可以看一看

### ISSUE THREAD

**Issue by 3498972895** [bz51/GeneticAlgorithm#5]
def main():
    import random
    import heapq
    import matplotlib.pyplot as plt
    from collections import namedtuple

    RandomRange = namedtuple("RandomRange", ["start", "end"])

    def roulette(fitness_probabilities):
        cumulative_probability = 0
        probability = random.random()
        for i in range(len(fitness_probabilities)):
            cumulative_probability += fitness_probabilities[i]
            if cumulative_probability >= probability:
                return i

    TASK_AMOUNT = 10
    SERVER_AMOUNT = 4
    CHROMOSOME_AMOUNT = 10
    ITERATION_COUNT = 100
    TASK_DATA_SIZE = RandomRange(start=5, end=20)
    SERVER_ABLITY = RandomRange(start=1, end=5)
    ITERATION_CHROMOSOMES_RESULT = []
    ITERATION_TIME_USEAGE_RESULT = []
    RESERVE_CHROMOSOME_COUNT = 2

    tasks = [
        random.randint(TASK_DATA_SIZE.start, TASK_DATA_SIZE.end)
        for _ in range(TASK_AMOUNT)
    ]
    servers = [
        random.randint(SERVER_ABLITY.start, SERVER_ABLITY.end)
        for _ in range(SERVER_AMOUNT)
    ]
    servers_tasks_matrix = [
        [round(tasks[j] / servers[i], 2) for j in range(TASK_AMOUNT)]
        for i in range(SERVER_AMOUNT)
    ]
    chromosomes = [
        [random.randint(0, SERVER_AMOUNT - 1) for _ in range(TASK_AMOUNT)]
        for _ in range(CHROMOSOME_AMOUNT)
    ]
    ITERATION_CHROMOSOMES_RESULT.append(chromosomes)
    ITERATION_TIME_USEAGE_RESULT.append(
        [
            sum(
                servers_tasks_matrix[server_index][task_index]
                for task_index, server_index in enumerate(chromosome)
            )
            for chromosome in chromosomes
        ]
    )
    for i in range(ITERATION_COUNT):
        fitness_marks = [1 / r for r in ITERATION_TIME_USEAGE_RESULT[i]]
        sum_fitness_marks = sum(fitness_marks)
        reserved = [
            ITERATION_CHROMOSOMES_RESULT[i][index]
            for index, mark in heapq.nlargest(
                RESERVE_CHROMOSOME_COUNT,
                [(index, mark) for index, mark in enumerate(fitness_marks)],
                key=lambda x: x[1],
            )
        ]
        fitness_probabilities = [mark / sum_fitness_marks for mark in fitness_marks]

        babies = []

        # cross
        for _ in range(CHROMOSOME_AMOUNT - RESERVE_CHROMOSOME_COUNT):
            chromosome_father = ITERATION_CHROMOSOMES_RESULT[i][
                roulette(fitness_probabilities)
            ]
            chromosome_mother = ITERATION_CHROMOSOMES_RESULT[i][
                roulette(fitness_probabilities)
            ]
            cutting_index = random.randint(0, TASK_AMOUNT - 1)
            baby = chromosome_father[:cutting_index] + chromosome_mother[cutting_index:]
            babies.append(baby)

        # mutation
        selected_baby = random.randint(
            0, CHROMOSOME_AMOUNT - RESERVE_CHROMOSOME_COUNT - 1
        )
        babies[selected_baby][random.randint(0, TASK_AMOUNT - 1)] = random.randint(
            0, SERVER_AMOUNT - 1
        )

        babies.extend(reserved)
        ITERATION_TIME_USEAGE_RESULT.append(
            [
                sum(
                    servers_tasks_matrix[server_index][task_index]
                    for task_index, server_index in enumerate(baby)
                )
                for baby in babies
            ]
        )
        ITERATION_CHROMOSOMES_RESULT.append(babies)
    flatten_itur = [min(row) for row in ITERATION_TIME_USEAGE_RESULT]
    plt.plot(flatten_itur)
    plt.show()

if __name__ == "__main__":
    main()

**Comment by zyx999** [comment]
你的邮件已收到，我将尽快阅读并回复，感谢你的来信！
